name: 자동 배포 테스트
on:
  workflow_dispatch:
  schedule: 
   - cron: "*/5 * * * *" #5분 마다 실행

jobs:
  merge:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2 # 저장소의 코드를 체크아웃(다운로드) 하는 역할
      - name: Merge upstream
        run: |
          git config --global user.name 'arkingco'
          git config --global user.email 'arkingco@gmail.com'
          git pull --unshallow 
          git remote add upstream https://github.com/Tinkerbell-Green/need-compliments.git
          git fetch upstream
          git checkout dev
          git merge -Xtheirs upstream/master
          git push origin dev